class AppCurrencies {
  static const Map<String, String> currencies = {
    "ATA5_YENI": "ATA Altın Yeni",
    "ATA5_ESKI": "ATA Altın Eski",
    "GREMESE_YENI": "Gram Altın Yeni",
    "GREMESE_ESKI": "Gram Altın Eski",
    "AYAR14": "Altın 14 Ayar",
    "GUMUSTRY": "Gümüş",
    "GUMUSUSD": "Gümüş USD",
    "AUDUSD": "AUD/USD",
    "GBPUSD": "GBP/USD",
    "PLATIN": "Platin",
    "PALADYUM": "Paladyum",
    "USDJPY": "USD/JPY",
    "USDCHF": "USD/CHF",
    "USDCAD": "USD/CAD",
    "EURUSD": "EUR/USD",
    "USDSAR": "USD/SAR",
    "NOKTRY": "NOK/TRY",
    "AUDTRY": "AUD/TRY",
    "ALTIN": "Altın",
    "USDPURE": "USD Pure",
    "USDTRY": "USD/TRY",
    "ONS": "Ons",
    "EURTRY": "EUR/TRY",
    "USDKG": "USD/KG",
    "EURKG": "EUR/KG",
    "AYAR22": "Altın 22 Ayar",
    "GBPTRY": "GBP/TRY",
    "CHFTRY": "CHF/TRY",
    "KULCEALTIN": "Külçe Altın",
    "XAUXAG": "XAU/XAG",
    "CEYREK_YENI": "Çeyrek Altın Yeni",
    "CADTRY": "CAD/TRY",
    "CEYREK_ESKI": "Çeyrek Altın Eski",
    "SARTRY": "SAR/TRY",
    "YARIM_YENI": "Yarım Altın Yeni",
    "YARIM_ESKI": "Yarım Altın Eski",
    "JPYTRY": "JPY/TRY",
    "TEK_YENI": "Tek Altın Yeni",
    "TEK_ESKI": "Tek Altın Eski",
    "ATA_YENI": "ATA Altın Yeni",
    "ATA_ESKI": "ATA Altın Eski",
    "DKKTRY": "DKK/TRY",
    "XAUUSD": "XAU/USD",
    "XAGUSD": "XAG/USD",
    "XPTUSD": "XPT/USD",
    "XPDUSD": "XPD/USD",
    "PLNTRY": "PLN/TRY",
    "HUFTRY": "HUF/TRY",
    "SEKTRY": "SEK/TRY",
    "ZARTRY": "ZAR/TRY",
    "ILSTRY": "ILS/TRY",
    "USDILS": "USD/ILS",
    "KWDUSD": "KWD/USD",
    "KWDTRY": "KWD/TRY",
    "JODTRY": "JOD/TRY",
    "JODUSD": "JOD/USD",
    "OMRUSD": "OMR/USD",
    "OMRTRY": "OMR/TRY"
  };
}